version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
  go-api:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: test_db
      DB_SSLMODE: disable
      API_PORT: 3033
    ports:
      - "3033:3033"
    depends_on:
      - postgres

